title: jekyll-rtd-theme
description: Just another documentation theme compatible with GitHub Pages

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

remote_theme:rundocs/jekyll-rtd-theme

url                      : "https://ageusgji.github.io" 
# the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" 
# the subpath of your site, e.g. "/blog"
locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
name                     : "AGEUSGJI"
description              : "An amazing website."

